CarDumpApp/Models/CreateSet/CreateSetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CarDumpApp.Models;

namespace CarDumpApp.Models
{
    public class CreateSetViewModel
    {
        public CarDumpSet CDSet { get; set; }
        public List<CarDump> Cardumps { get; set; }
        //public AutoModel AutoModel { get; set; }
       
    }
}

CarDumpApp/Controllers/Production/CreateSetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDumpApp.Models;
using Microsoft.AspNet.Identity;
namespace CarDumpApp.Controllers.Production
{
    public class CreateSetsController :Controller
    {
        CarDumpDatabaseEntities db = new CarDumpDatabaseEntities();
        // GET: CreateSets
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            var lst = (from s in db.CarDumpSets where s.PostedUserID == id select s).ToList();
            return View(lst);
        }

        public ActionResult IndexPartial()
        {
            string id = User.Identity.GetUserId();
            var lst = (from s in db.CarDumpSets where s.PostedUserID == id select s).ToList();
            return PartialView(lst);
        }

        [HttpGet]
        public ActionResult Create()
        {
            //welcome screen
            return View();
        }

        [HttpPost]
        public void Save(CreateSetViewModel mdl)
        {
            try
            {
                CarDumpSet set = db.CarDumpSets.Where(tf => tf.Id == mdl.CDSet.Id).First();
                set.Description = mdl.CDSet.Description;
                db.Entry(set).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
          
            }
            catch(Exception)
            {

            }

        }


        [HttpPost]
        public int Create(int cardumpitem)
        {
            using(var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    CarDump cdi = (from c in db.CarDumps where c.Id == cardumpitem select c).First();//.ToList()[0];
                    CarDumpSet cds = new CarDumpSet()
                    {
                        ModelId = cdi.AutoModelId,
                        CreatedDate = DateTime.Now,
                        Description = "empty description",
                        Year = cdi.Year,
                        PostedUserID = User.Identity.GetUserId()

                    };
                    db.CarDumpSets.Add(cds);
                    db.SaveChanges();
                    SetItem si = new SetItem()
                    {
                        CarDumpID = cardumpitem,
                        CarDumpSetID = cds.Id
                    };
                    db.SetItems.Add(si);
                    db.SaveChanges();


                    transaction.Commit();
                    return cds.Id;

                }
                catch(Exception ex)
                {
                    transaction.Rollback();
                    return -1;
                }
            }







        }




        public ActionResult EditSet(int? SetItem)
        {
            CreateSetViewModel mdl = new CreateSetViewModel();
            if(SetItem != null)
            {
                try
                {
                    CarDumpSet set = (from s in db.CarDumpSets where s.Id == SetItem select s).First();
                    mdl.CDSet = set;

                    return View(mdl);
                }
                catch(Exception)
                {
                    return HttpNotFound();
                }

            }
            else return HttpNotFound();





        }


        [HttpPost]
        public ActionResult EditSet(int? SetItem, int? cditem, string saction)
        {
            CreateSetViewModel mdl = new CreateSetViewModel();
            if(SetItem != null)
            {
                try
                {
                    CarDumpSet set = (from s in db.CarDumpSets where s.Id == SetItem select s).First();

                    switch(saction)
                    {
                        case "add":
                            {
                                var slist = set.SetItems.OrderBy(ts => ts.Id).ToList();
                                if(slist.Find(tf => tf.CarDumpID == cditem) == null)
                                {
                                    SetItem si = new Models.SetItem();
                                    si.CarDumpID = (int)cditem;
                                    si.CarDumpSetID = set.Id;
                                    db.SetItems.Add(si);
                                    db.SaveChanges();
                                    db.Dispose();
                                    db = new CarDumpDatabaseEntities();
                                    return EditSet(SetItem, 0, "");
                                }
                                break;
                            }

                        case "rem":
                            {
                                //   List<SetItem> SI = set.SetItems.Where(s => s.Id == cditem).ToList();

                                //MemoryType memoryType = db.MemoryTypes.Find(id);
                                //db.MemoryTypes.Remove(memoryType);
                                //db.SaveChanges();
                                //return RedirectToAction("Index");

                                SetItem SI = db.SetItems.Find(cditem);
                                db.SetItems.Remove(SI);
                                db.SaveChanges();



                                db.Dispose();
                                db = new CarDumpDatabaseEntities();
                                return EditSet(SetItem, 0, "");
                            }

                        default: break;
                    }

                    mdl.CDSet = set;
                    return PartialView("EditSetPartial", mdl);
                }
                catch(Exception)
                {
                    return HttpNotFound();
                }

            }
            else return HttpNotFound();

        }

    }
}

CarDumpApp/Views/CreateSets/Create.cshtml
@using Microsoft.AspNet.Identity


@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}


<h3>Click on item below to create set</h3>

@{Html.RenderAction("CarDumpsListByUserId", "AdminPanel", new
    {
        userId = User.Identity.GetUserId()
    });}



@section scripts{
 
    <script type="text/javascript">
        $(".trline").click(function () {
            var s1 = $(this).find('td:first').attr('cid');
            var navS = '@Url.Action("Create")' + '/?cardumpitem=' + s1;
            //  alert(navS);
            //$(location).attr('href', navS);


            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create")/?cardumpitem='+s1,
                success: function (data) {
                    //$('#SearchResult').replaceWith(data);
                    //alert(data);
                    if (data!=-1)
                    $(location).attr('href', '@Url.Action("EditSet")/?SetItem='+data);
                }
               ,
                error: function (xhr, status, p3) {
                    alert(xhr.responseText);
                }
            });


        });
    </script>
 
    }

CarDumpApp/Views/CreateSets/EditSet.cshtml
@using Microsoft.AspNet.Identity
@model CarDumpApp.Models.CreateSetViewModel




<div class="container">
    <div class="row">
        <h4>@Model.CDSet.AutoModel.AutoBrand.Name @Model.CDSet.AutoModel.Name @Model.CDSet.Year  </h4>
        @using(Html.BeginForm("Save", "CreateSets", FormMethod.Post, new { @id = "FMAIN" }))
        {
            @Html.HiddenFor(model => model.CDSet.Id)
            <label>Short description about set </label>
            <br />
            @Html.TextAreaFor(model => model.CDSet.Description, new { rows = "10", cols = "45" })
            <br />
            <label id="savereturn" style="margin:4px; color:#07b415;"></label>
            <br />
            <input type="submit" value="Save" class="btn btn-success" />
            @*<button name="action" value="delete">Удалить</button>*@
        }
    </div>





    <div class="row">
        <hr />
        @Html.Partial("EditSetPartial", Model)

    </div>

    <div class="row">

    </div>
    <div class="row">
        <hr />
        <h3>Click on item below to add to set</h3>

        @{Html.RenderAction("CarDumpsListByUserId", "AdminPanel", new
            {
                userId = User.Identity.GetUserId(),
                modelID = Model?.CDSet?.ModelId,
                year = Model?.CDSet?.Year
            });}
    </div>


</div>





@section scripts{

    <script type="text/javascript">


        $('#FMAIN').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url: $(this).attr('action') || window.location.pathname,
                type: "POST",
                data: $(this).serialize(),
                success: function (data) {
                    //    alert('ok');
                    // alert($('#savereturn').text());
                    $('#savereturn').text('saved');
                    setTimeout(function () {
                        $('#savereturn').text('');
                    }, 1000);


                },
                error: function (jXHR, textStatus, errorThrown) {
                    //    alert(errorThrown);
                }
            });
        });


        $(".trline").click(function () {
            var id = $("#SID").val();
            var cardumpid = $(this).find('td:first').attr('cid');
            var act = "add";


            $.ajax({
                type: 'POST',
                url: '@Url.Action("EditSet")/?SetItem=' + id + '&cditem=' + cardumpid + '&saction=' + act,
                success: function (data) {
                    $('#EditSetPartialView').replaceWith(data);

                    $(".rembtn").click(initDel);

                }
               ,
                error: function (xhr, status, p3) {
                    alert(xhr.responseText);
                }
            });


        });


        function initDel() {
            var id = $("#SID").val();
            var cdid = $(this).attr("cdid");
            var act = "rem";
            //  alert(cdid+" "+id);
            $.ajax({
                type: 'POST',
                url: '@Url.Action("EditSet")/?SetItem=' + id + '&cditem=' + cdid + '&saction=' + act,
                success: function (data) {

                    $('#EditSetPartialView').replaceWith(data);
                    $(".rembtn").click(initDel);
                }
              ,
                error: function (xhr, status, p3) {
                    alert(xhr.responseText);
                }
            });

        }
        $(".rembtn").click(initDel);

    </script>

}

CarDumpApp/Views/CreateSets/EditSetPartial.cshtml
@model CarDumpApp.Models.CreateSetViewModel


<div id="EditSetPartialView">

    
    <input type="text" value="@Model.CDSet.Id" id="SID" hidden />
    <h3>This is list of files in Set</h3>

    <ul class="list-group">
        @foreach(var item in Model.CDSet.SetItems)
        {
            <li class="list-group-item" style="margin:2px;">
                @Html.ActionLink(item.CarDump.PersonalNumber, "Create", "CreateCarDumpRecord", null, new { id= item.Id }) |
               
                @item.CarDump.Module.Name |
                @item.CarDump.ModuleNumber |
                @item.CarDump.AutoModel.Name |
                @item.CarDump.AutoModel.AutoBrand.Name |

                @item.CarDump.ModuleNumber

                <span class="rembtn" cdid="@item.Id" style="color:red; cursor:pointer;">remove from set</span>
            </li>
        }
    </ul>
</div>

CarDumpApp/Views/CreateSets/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<CarDumpApp.Models.CarDumpSet>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_AdminView.cshtml";
}

<h2>List of sets</h2>
@Html.ActionLink("Create new","Create");


<ul class="list-group">
    @foreach(var item in Model)
    {
        <li class="list-group-item">
            @item.AutoModel.Name
            @Html.ActionLink("Edit", "EditSet", new { @SetItem=item.Id });
        </li>

    }

</ul>

CarDumpApp/Views/CreateSets/IndexPartial.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<CarDumpApp.Models.CarDumpSet>

@Html.ActionLink("Create new", "Create",null, new {@class="btn btn-success" })


<ul class="list-group">
    @foreach(var item in Model)
    {
        <li class="list-group-item">
            @item.AutoModel.AutoBrand.Name
            @item.AutoModel.Name
            @item.Year
            @item.Description
            @Html.ActionLink("Edit", "EditSet", new { @SetItem = item.Id  }, new { @class = "btn btn-info" })
        </li>
    }

</ul>