CarDumpApp/Models/Module.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.CarDumps = new HashSet<CarDump>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDump> CarDumps { get; set; }
    }
}

CarDumpApp/Controllers/Production/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDumpApp.Models;
namespace CarDumpApp.Controllers.Production
{
    public class ModuleController : Controller
    {
        CarDumpDatabaseEntities db = new CarDumpDatabaseEntities();
        // GET: Module
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult ModalWindow()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult ModalWindow(Module mdl)
        {
            if (mdl is Module)
            {
                db.Modules.Add(mdl);
                db.SaveChanges();
            }
            ViewBag.DDListModule = new SelectList(db.Modules, "Id", "Name");
            return PartialView("DDListModule");
        }
        public ActionResult DDListModule(Module mdl)
        {
            ViewBag.DDListModule = new SelectList(db.Modules, "Id", "Name",mdl?.Id);
            return PartialView();
        } 
    }
}

CarDumpApp/Views/Module/DDListModule.cshtml
@Html.DropDownList("DDListModule", null, htmlAttributes: new { @class = "form-control" })

CarDumpApp/Views/Module/ModalWindow.cshtml
@model CarDumpApp.Models.Module


@using(Ajax.BeginForm("ModalWindow", "Module", new AjaxOptions { UpdateTargetId = "ddlist-module" }, new { id = "moduleformadd" }))
{


    <!-- Modal -->
    <div id="modal-moduleadd" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div style="background-color:#1a6358;border-radius: 5px 5px  0 0 ;" class="modal-header">
                    <button type="button" style="color:white" class="close" data-dismiss="modal">&times;</button>
                    <h4 style="color:white" class="modal-title">Add Module Type</h4>
                </div>
                <div class="modal-body">

                    @Html.EditorFor(model => model.Name, "", new { htmlAttributes = new { @class = "form-control" } })




                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-md" form="moduleformadd" value="Submit"  style="background-color:#1a6358;color:white;border-color:#1a6358 ;" onclick="$('#modal-moduleadd').modal('hide');">Submit</button>
                </div>
            </div>

        </div>
    </div>

}