CarDumpApp/Controllers/Production/CreateAutoBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDumpApp.Models;

namespace CarDumpApp.Controllers.Production
{
    public class CreateAutoBrandController :Controller
    {
        CarDumpDatabaseEntities db = new CarDumpDatabaseEntities();
        // GET: CreateAutoBrand
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult ModalWindow()
        {
            ViewBag.CurrenBrands = new SelectList(db.AutoBrands, "Id", "Name");
            return PartialView();
        }

        [HttpPost]
        public ActionResult ModalWindow(AutoBrand brand, string mm)
        {
            if(brand is AutoBrand)
            {
                db.AutoBrands.Add(brand);
                db.SaveChanges();

            }

            ViewBag.CurrenBrands = new SelectList(db.AutoBrands, "Id", "Name");
            ViewBag.DDListAutoBrand = new SelectList(db.AutoBrands, "Id", "Name");
            ViewBag.DDListAutoModel = new SelectList(db.AutoModels, "Id", "Name");
            return PartialView("DDListAutoBrand");
        }

        public ActionResult DDListAutoBrand(AutoBrand br, AutoModel mdl)
        {

            AutoBrand sel = null;
            if(mdl is AutoModel)
            {
                sel = mdl.AutoBrand;
            }
            else if(br != null)
                sel = br;

            if(sel == null)
                sel = (from c in db.AutoBrands select c).ToList()[0];

            ViewBag.DDListAutoBrand = new SelectList(db.AutoBrands, "Id", "Name", sel?.Id);
            ViewBag.DDListAutoModel = new SelectList(db.AutoModels.Where(tf => tf.AutoBrandID == sel.Id), "Id", "Name", mdl?.Id);
            return PartialView();
        }



        public ActionResult ModelsByBrand(int? id)
        {
            ViewBag.DDListAutoModel = new SelectList(db.AutoModels.Where(c => c.AutoBrandID == id), "Id", "Name");

            return PartialView();
        }
        public ActionResult ModelsByBrandE(int? id)
        {
            ViewBag.AutoModelID = new SelectList(db.AutoModels.Where(c => c.AutoBrandID == id), "Id", "Name");

            return PartialView();
        }

    }
}

CarDumpApp/Views/CreateAutoBrand/DDListAutoBrand.cshtml
    @Html.DropDownList("DDListAutoBrand", null, htmlAttributes: new { @class = "form-control" })

    @Html.DropDownList("DDListAutoModel", null, htmlAttributes: new { @class = "form-control" })

   

CarDumpApp/Views/CreateAutoBrand/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#modal-AutobrandAdd">Open Modal</button>

 @{ Html.RenderAction("ModalWindow","CreateAutoBrand");}

CarDumpApp/Views/CreateAutoBrand/ModalWindow.cshtml
@model CarDumpApp.Models.AutoBrand


@using(Ajax.BeginForm("ModalWindow", "CreateAutoBrand", new AjaxOptions { UpdateTargetId = "ddlist-autobrand" }, new { id="AddAutoForm" }))
{
<!-- Modal -->
<div id="modal-AutobrandAdd" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div style="background-color:#1a6358;border-radius: 5px 5px  0 0 ;" class="modal-header">
                <button type="button" style="color:white" class="close" data-dismiss="modal">&times;</button>
                     <h4 style="color:white" class="modal-title">Add Auto Brand</h4>
            </div>

            <div class="modal-body">
                    @*@Html.DropDownList("CurrenBrands", null, htmlAttributes: new { @class = "form-control" })*@
                    @Html.EditorFor(model => model.Name, "", new { htmlAttributes = new { @class = "form-control" } })
            </div>
             <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-md" form="AddAutoForm" value="Submit" style="background-color:#1a6358;color:white;border-color:#1a6358 ;" onclick="$('#modal-AutobrandAdd').modal('hide');">Submit</button>
             </div>
        </div>
    </div>
</div>
 
}

@*@using(Html.BeginForm("ModalWindow", "CreateAutoBrand",FormMethod.Post))*@

CarDumpApp/Views/CreateAutoBrand/ModelsByBrand.cshtml
@Html.DropDownList("DDListAutoModel", null, htmlAttributes: new { @class = "form-control" })

CarDumpApp/Views/CreateAutoBrand/ModelsByBrandE.cshtml
@Html.DropDownList("AutoModelID", null, htmlAttributes: new { @class = "form-control" })